import {
  MotionDiv,
  MotionSection,
  MotionMain,
  MotionFooter,
  MotionHeader,
  MotionNav,
  MotionAside,
  MotionArticle,
  MotionH1,
  MotionH2,
  MotionH3,
  MotionH4,
  MotionH5,
  MotionH6,
  MotionP,
  MotionSpan,
  MotionButton,
  MotionA,
  MotionImg,
  MotionLi,
  MotionUl,
  MotionOl,
  MotionTr,
  MotionTd,
  MotionTh,
  MotionTable,
  MotionForm,
  MotionInput,
  MotionTextarea,
  MotionLabel,
  MotionSvg,
  MotionPath,
  MotionCircle,
  MotionRect,
  MotionLine,
  MotionPolygon,
  MotionPolyline,
  MotionEllipse,
  MotionG,
  MotionDefs,
  MotionLinearGradient,
  MotionRadialGradient,
  MotionStop,
  MotionClipPath,
  MotionMask,
} from './motion-wrapper';

export const motion = {
  div: MotionDiv,
  section: MotionSection,
  main: MotionMain,
  footer: MotionFooter,
  header: MotionHeader,
  nav: MotionNav,
  aside: MotionAside,
  article: MotionArticle,
  h1: MotionH1,
  h2: MotionH2,
  h3: MotionH3,
  h4: MotionH4,
  h5: MotionH5,
  h6: MotionH6,
  p: MotionP,
  span: MotionSpan,
  button: MotionButton,
  a: MotionA,
  img: MotionImg,
  li: MotionLi,
  ul: MotionUl,
  ol: MotionOl,
  tr: MotionTr,
  td: MotionTd,
  th: MotionTh,
  table: MotionTable,
  form: MotionForm,
  input: MotionInput,
  textarea: MotionTextarea,
  label: MotionLabel,
  svg: MotionSvg,
  path: MotionPath,
  circle: MotionCircle,
  rect: MotionRect,
  line: MotionLine,
  polygon: MotionPolygon,
  polyline: MotionPolyline,
  ellipse: MotionEllipse,
  g: MotionG,
  defs: MotionDefs,
  linearGradient: MotionLinearGradient,
  radialGradient: MotionRadialGradient,
  stop: MotionStop,
  clipPath: MotionClipPath,
  mask: MotionMask,
};

export default motion;
