# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: '70...100'

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_ci_failed: error

    patch:
      default:
        target: 80%
        threshold: 1%

  ignore:
    - 'src/**/*.test.ts'
    - 'src/**/*.test.tsx'
    - 'src/**/*.spec.ts'
    - 'src/**/*.spec.tsx'
    - 'src/test/**/*'
    - 'src/**/__tests__/**/*'
    - 'src/**/*.stories.tsx'
    - 'src/**/*.d.ts'
    - 'vite.config.ts'
    - 'vitest.config.ts'
    - 'tailwind.config.js'
    - 'postcss.config.js'

comment:
  layout: 'reach,diff,flags,tree'
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

github_checks:
  annotations: true
